### ISSUE TITLE
TestBed or documentation

### ISSUE THREAD

**Issue by MarketStalker** [lorendsnow/IBKRWrapper#1]
Hello is there any testbed or example projects for this. I am very interested and have been looking for something exactly like this. I am specifically interested in the news, realtime charting and examples of custom scans. Hard to find examples of the new API in use so this looks very promising.

**Comment by lorendsnow** [comment]
No docs or tests at the moment, I've just been sort of implementing things as and when I need them for other applications, and just threw it up here in case the code might be useful to others. At some point I may try to organize this into something a little more cohesive with some basic documentation (or at least xml documentation in the code), but in the meantime feel free to use it / fork it, and play around with it.

**Comment by MarketStalker** [comment]
Thank you, I have found the api difficult to use and debugging their test app was a pain. Thank you for providing this. I saw your solution was referencing a ManualTest project which I was hoping to take a look at to see how you were using the wrapper, is there any chance this part is available erven unofficially,  otherwise I will just try and decipher it, was hoping to understand how to use the wrapper without reinventing the wheel, Either way thanks for your effort  and sharing
